#!/bin/bash

cd ~/

git config --global user.name XenonTheInertG
git config --global user.email XenonTheInertG@outlook.com

# Sync stuffs
git clone https://github.com/F1xy-kernels/RAPHAEL_Kernel --depth=1 --single-branch -b R-raphael
