name: Recovery-CI2
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

env:
  MANIFEST: "https://github.com/SHRP/platform_manifest_twrp_omni"
  DT_LINK: "https://github.com/SHRP-Devices/device_realme_RMX1801"
  VENDOR: "realme"
  CODENAME: "RMX1801"
  KERNEL_LINK: ""
  TARGET: "recoveryimage"
  FLAVOR: "eng"
  EXTRA_CMD: ""
  TZ: "Asia/Dhaka"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: rokibhasansagar/slimhub_actions@main
    - name: Build Image
      uses: XenonTheInertG/android-recovery-action@main
