name: "Kernel-CI5"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: "Build Unitrix kernel"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout kernel source"
      uses: actions/checkout@v2
      with:
        repository: Blacksuan19/kernel_dark_ages_vince

    - name: "Set variables"
      id: vars
      run: |
        echo "::set-output name=short_sha::$(git rev-parse HEAD | cut -b 1-8 -)"
        echo "::set-output name=release_name::Dark-Ages-Último"

    - name: "Checkout zipper"
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: "Pre-build message to Telegram"
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.BOT_API }}
        message: Building ${{ steps.vars.outputs.release_name }} on ${{ steps.vars.outputs.short_sha }}. https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: "Android kernel build"
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: ${{ steps.vars.outputs.release_name }}
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: vince_defconfig
        image: Image.gz-dtb

    - name: "Post build to Telegram"
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.BOT_ID }}
        message: ${{ steps.vars.outputs.release_name }} on ${{ steps.vars.outputs.short_sha }} is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.
        document: ${{ steps.build.outputs.outfile }}
        
    - name: "Alert failed build"
      uses: appleboy/telegram-action@master
      if: ${{ failure() }}
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.BOT_API }}
        message: Failed building ${{ steps.vars.outputs.release_name }} on ${{ steps.vars.outputs.short_sha }}, check action for more info.
