name: Dump-CI
 
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  ROM_URL: https://bigota.d.miui.com/V12.5.4.0.RKJINXM/ares_in_global_images_V12.5.4.0.RKJINXM_20210721.0000.00_11.0_in_f38f58a6cb.tgz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Tools
         run: |
              git clone https://github.com/XenonTheInertG/Xenon-CI

       - name: Setup Dumpyara environment
         working-directory: Xenon-CI
         run: |
              sudo bash setup.sh
              git config --global user.name "XenonTheInertG"
              git config --global user.email "XenonTheInertG@outlook.com"

       - name: Setup config envs
         working-directory: Xenon-CI
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .github_token
              echo "${{ secrets.ORG }}" > .github_orgname
              echo "${{ secrets.BOT_API }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Running tools
         working-directory: Xenon-CI
         run: |
              ./dump.sh "$ROM_URL"
