name: Dump-CI
 
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  ROM_URL: https://mgb1.androidfilehost.com/dl/yF8EkxlKubBI53Brcinq3A/1637760417/2188818919693773244/Walton_Primo_R6_Max_S06_08072019_SPD_%28by_firmwarefile.com%29.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Tools
         run: |
              git clone https://github.com/Xenon-s-Workshop/firmware_dumper dump

       - name: Setup Dumpyara environment
         working-directory: dump
         run: |
              sudo bash setup.sh
              git config --global user.name "XenonTheInertG"
              git config --global user.email "XenonTheInertG@outlook.com"

       - name: Setup config envs
         working-directory: dump
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .github_token
              echo "${{ secrets.ORG }}" > .github_orgname
              echo "${{ secrets.BOT_API }}" > .tg_token
              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Running tools
         working-directory: dump
         run: |
              ./dump.sh "$ROM_URL"
